#!/usr/bin/env bash
# Delete orphaned AI imagery (generated after the text-led cleanup).
# KEEPS: returns/*, founders headshots, logo-b*, brand/*, heroBG, favicon.
# Run from the repo root:  bash _delete-ai-images.sh
set -e
cd "$(dirname "$0")"
rm -f "public/images/bitmap.b.data.map.png"
rm -f "public/images/bitmap.b.data.map.webp"
rm -f "public/images/bitmap.cityscape.muted.webp"
rm -f "public/images/bitmap.data.b.png"
rm -f "public/images/cta-texture-128.webp"
rm -f "public/images/cta-texture-32.webp"
rm -f "public/images/cta-texture-64.webp"
rm -f "public/images/heroes/hero-about-two-minds-03.webp"
rm -f "public/images/heroes/hero-data-meets-emotion-07.webp"
rm -f "public/images/heroes/hero-uiux-transparent-02.webp"
rm -f "public/images/home-hero-cube-transparent.png"
rm -f "public/images/home-hero-cube-transparent_2.png"
rm -f "public/images/listening.woman.png"
rm -f "public/images/listening.woman2.emptyBook.png"
rm -f "public/images/listening.woman2.emptyBook.webp"
rm -f "public/images/listening.woman2.emptyHands.png"
rm -f "public/images/listening.woman2.emptyHands.webp"
rm -f "public/images/listening.woman2.png"
rm -f "public/images/listening.woman2.train.png"
rm -f "public/images/listening.woman2.train.webp"
rm -f "public/images/listening.woman2.webp"
rm -f "public/images/stalking.sabretooth.png"
rm -f "public/images/stalking.sabretooth.webp"
rm -f "src/assets/images/about-bitmap-philosophy-bg-01.png"
rm -f "src/assets/images/contact-details-bg-04.png"
rm -f "src/assets/images/deliverables-bg-01.png"
rm -f "src/assets/images/hero-about-two-minds-03.png"
rm -f "src/assets/images/hero-contact-07.png"
rm -f "src/assets/images/hero-data-meets-emotion-07.png"
rm -f "src/assets/images/hero-faq-10.png"
rm -f "src/assets/images/hero-footer-04.png"
rm -f "src/assets/images/hero-immersive-audio-01.png"
rm -f "src/assets/images/hero-immersive-audio-06.png"
rm -f "src/assets/images/hero-immersive-audio-13.png"
rm -f "src/assets/images/hero-sonic-branding-transparent-03.png"
rm -f "src/assets/images/hero-uiux-transparent-01.png"
rm -f "src/assets/images/hero-uiux-transparent-02.png"
rm -f "src/assets/images/hero-uiux-transparent-03.png"
rm -f "src/assets/images/hero-uiux-transparent-03_2.png"
rm -f "src/assets/images/home-hero-sonic-infrastructure-01.png"
rm -f "src/assets/images/home-hero-sonic-infrastructure-02.png"
rm -f "src/assets/images/home-hero-sonic-infrastructure-03.png"
rm -f "src/assets/images/home-hero-sonic-infrastructure-04.png"
rm -f "src/assets/images/home-our-philosophy-bg-06.png"
echo "Deleted orphaned AI imagery."
